In [34]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
full_data = pd.read_pickle('../data/processed/full_data.pkl')

In [3]:
# newyork_2015 = pd.DataFrame(full_data.loc[(full_data['year']==2015) & (full_data['region'] == 'New York')].groupby('week')['sales'].sum()).reset_index()
full_data = full_data.drop(columns=['yearweek', 'days', 'd'])

In [10]:
full_data['event'] = full_data['event'].fillna(False)
full_data.loc[full_data['event'] != False, 'event'] = True
# full_data[full_data['event'] != False].head(100)

,item,category,department,store_code,region,sales,date,weekday,weekday_int,event,year,month,day,week,sell_price
243927,ACCESORIES_1_008,ACCESORIES,ACCESORIES_1,NYC_1,New York,7,2011-02-06,Sunday,2,True,2011,2,6,05,0.6118
243928,ACCESORIES_1_009,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,2.0748
243929,ACCESORIES_1_010,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,4.2161
243931,ACCESORIES_1_012,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,7.9534
243934,ACCESORIES_1_015,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,0.9310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244194,ACCESORIES_1_282,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,5.6126
244198,ACCESORIES_1_286,ACCESORIES,ACCESORIES_1,NYC_1,New York,17,2011-02-06,Sunday,2,True,2011,2,6,05,0.9310
244200,ACCESORIES_1_288,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,0.6251
244201,ACCESORIES_1_289,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,6.6101
244202,ACCESORIES_1_290,ACCESORIES,ACCESORIES_1,NYC_1,New York,0,2011-02-06,Sunday,2,True,2011,2,6,05,7.1288

In [12]:
full_data['total_sales'] = full_data['sales'] * full_data['sell_price']

In [67]:
full_data.to_pickle('../data/processed/full_data.pkl')